---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

```{r setup}
#| include: false
targets::tar_config_set(store = here::here("_targets"))
# to show Quarto that it needs to find the Targets file in a different folder (then /doc)
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r}
tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites")
```

```{r}
tar_read(fig_metabolite_distribution) +
  ggprism::theme_prism()
```

## Building the model

```{r}
lipidomics_wide <- lipidomics %>%
  column_values_to_snake_case(metabolite) %>%
  metabolites_to_wider(metabolite)

lipidomics_wide
```

## Running multiple models

```{r}

lipidomics %>% calculate_estimates()

```

## Fixing metabolite names

```{r}
lipidomics %>% 
    select(metabolite) %>% 
    mutate(term = metabolite) %>% 
    column_values_to_snake_case(term) %>% 
    mutate(term = str_c("metabolite_", term)) %>% 
    distinct(metabolite, term) %>% 
    right_join(model_estimates, by = "term")


```
